### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by congle-ibl** [input-output-hk/project-icarus-importer#4]
I built script for running blockchain importer with this command:
`nix-build -A connectScripts.mainnetBlockchainImporter -o import_mainnet.sh`

Then, I ran the script and got this issue:
`cardano-blockchain-importer: libpq: failed (fe_sendauth: no password supplied)`

After that, I created a new postgre database and modified script import_mainnet.sh with adding some fields and ran again
`
--postgres-name “icaruspocbackendservice”
--postgres-user “postgres”
--postgres-password “mysecretpassword”
--postgres-host “localhost”
--postgres-port 5432
`

But I got a new issue like this
`
[importer:ERROR:ThreadId 7] [2018-08-22 10:37:06.31 UTC] logException: SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"txs\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
cardano-blockchain-importer: SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"txs\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
./import_mainnet.sh: line 49: +RTS: command not found
`

Please help to provide a full guide for building and running this project, thank you so much

**Comment by AlanVerbner** [comment]
Hi @congle-ibl ... you should create DB tables first. Please try running this script https://github.com/input-output-hk/project-icarus-importer/blob/54812808703274919e2441fd8050eb5bfedc2539/scripts/generate/blockImporterTables-beta.sql#L1

**Comment by congle-ibl** [comment]
Hi @AlanVerbner 

Thank you so much for your help, after running this script, everything worked fine
