### ISSUE TITLE
Can NOT build with mainnetExplorer mode

### ISSUE THREAD

**Issue by congle-ibl** [input-output-hk/project-icarus-importer#5]
Hi everyone,

I am using this command to build the project with "mainnetExplorer" mode:
`nix-build -A connectScripts.mainnetExplorer -o explorer_mainnet.sh` 

But I met the below issue. Could you please help take a look and suggest me what to do now? Thank you so much.
`
src/Pos/Explorer/Txp/Local.hs:83:5: error:
    • Couldn't match type ‘Maybe ()’ with ‘()’
      Expected type: m ()
        Actual type: m (Maybe ())
    • In a stmt of a 'do' block:
        txNormalizeAbstract
          buildExplorerExtraLookup (normalizeToil' extras)
      In the expression:
        do { extras <- MM.insertionsMap . view eemLocalTxsExtra
                       <$> withTxpLocalData getTxpExtra;
             txNormalizeAbstract
               buildExplorerExtraLookup (normalizeToil' extras) }
      In an equation for ‘eTxNormalize’:
          eTxNormalize
            = do { extras <- MM.insertionsMap . view eemLocalTxsExtra
                             <$> withTxpLocalData getTxpExtra;
                   txNormalizeAbstract
                     buildExplorerExtraLookup (normalizeToil' extras) }
            where
                normalizeToil' ::
                  HashMap TxId TxExtra
                  -> BlockVersionData
                     -> EpochIndex -> HashMap TxId TxAux -> ELocalToilM ()
                normalizeToil' extras bvd epoch txs
                  = let ... in eNormalizeToil bvd epoch toNormalize
[30 of 30] Compiling Pos.Arbitrary.Explorer ( src/Pos/Arbitrary/Explorer.hs, dist/build/Pos/Arbitrary/Explorer.o )
builder for '/nix/store/fl1apaayh1spd3677w91l84mk1ns0b10-cardano-sl-explorer-1.1.1.drv' failed with exit code 1
cannot build derivation '/nix/store/7yn62yv5w6f9llb81y7p5rb15hfd66kl-explorer-connect-to-mainnet.drv': 1 dependencies couldn't be built
error: build of '/nix/store/7yn62yv5w6f9llb81y7p5rb15hfd66kl-explorer-connect-to-mainnet.drv' failed
`

**Comment by ntallar** [comment]
Hi @congle-ibl !

For building and starting the project on mainnet the following commands can be used (they start the importer, not the explorer):
- `./scripts/build/cardano-sl.sh blockchain-importer`
- `printf "wallet:\n relays: [[{ host: relays.cardano-mainnet.iohk.io  }]]\n valency: 1\n fallbacks: 7" > "/tmp/topology.yaml"`
- `stack exec -- cardano-blockchain-importer --topology "/tmp/topology.yaml" --log-config "blockchain-importer/log-config.yaml" --logs-prefix "logs/mainnet" --db-path db-mainnet --keyfile "secret-mainnet.key" --configuration-file "lib/configuration.yaml" --configuration-key mainnet_full --postgres-name ${POSTGRES_NAME} --postgres-password ${POSTGRES_PASSWORD}`

The commands for building with nix will be added on a later stage. Note that the project has **NO full support** for the mainnet, for now the project is intended to be used only on the Cardano testnet.

**Comment by congle-ibl** [comment]
Hi @ntallar 

Thank you so much for your quick support. But I don't really understand what you mean about not supporting for mainnet, because I built and ran blockchain-importer successfully with mainnet and didn't know how to do the same thing with testnet.

**Comment by ntallar** [comment]
@congle-ibl The importer was tested and works with the mainnet, what I meant that you should just be careful about using this with the extension that you'll be moving funds on the mainnet.

**Comment by congle-ibl** [comment]
@ntallar Thank you so much for your help
