### ISSUE TITLE
How to build a docker image?

### ISSUE THREAD

**Issue by gutenye** [input-output-hk/project-icarus-importer#8]
From the [docker-compose.yaml](https://github.com/input-output-hk/project-icarus/blob/master/docker-compose.yaml), it said `TODO: push to docker hub`.

How can I build the docker image locally?

**Comment by mirkoAlic** [comment]
Guys @Profpatsch, @gdeest, would you give some output here please?

**Comment by Profpatsch** [comment]
You need to build it with nix for now:

```
nix-build -A dockerImages.testnetBlockchainImporter --out-link cardano-container-testnet-image.tar.gz importer/default.nix
$ docker load -i cardano-container-testnet-image.tar.gz
```

The build is going to take a while (about 30–60 minutes on my laptop).

**Comment by gutenye** [comment]
@Profpatsch Thanks, will try it. I'm going to mark it as resolved.
