### ISSUE TITLE
Icarus importer was stuck due to error of postgresql

### ISSUE THREAD

**Issue by congle-ibl** [input-output-hk/project-icarus-importer#9]
Hi everyone,

I have run icarus-importer for a long time ago and it worked smoothly. But yesterday, I got an error with it, and it couldn't import anymore, please help to take a look and give me some advice. Thank you so much for your time.

`1|import_mainnet  | [importer:WARNING:ThreadId 1213] [2018-11-08 03:38:55.26 UTC] handleRecoveryE: error handling nodeId="13.228.109.114:3000:0", header=1cc3f5189beb52d0: SqlError {sqlState = "54000", sqlExecStatus = FatalError, sqlErrorMsg = "index row requires 10520 bytes, maximum size is 8191", sqlErrorDetail = "", sqlErrorHint = ""}`

`1|import_mainnet  | [importer:WARNING:ThreadId 1213] [2018-11-08 03:38:55.26 UTC] Recovery mode communication dropped with peer "13.228.109.114:3000:0"`

Best Regards.

**Comment by wangsai-silence** [comment]
> Hi everyone,
> 
> I have run icarus-importer for a long time ago and it worked smoothly. But yesterday, I got an error with it, and it couldn't import anymore, please help to take a look and give me some advice. Thank you so much for your time.
> 
> `1|import_mainnet | [importer:WARNING:ThreadId 1213] [2018-11-08 03:38:55.26 UTC] handleRecoveryE: error handling nodeId="13.228.109.114:3000:0", header=1cc3f5189beb52d0: SqlError {sqlState = "54000", sqlExecStatus = FatalError, sqlErrorMsg = "index row requires 10520 bytes, maximum size is 8191", sqlErrorDetail = "", sqlErrorHint = ""}`
> 
> `1|import_mainnet | [importer:WARNING:ThreadId 1213] [2018-11-08 03:38:55.26 UTC] Recovery mode communication dropped with peer "13.228.109.114:3000:0"`
> 
> Best Regards.

Hi, recently I'm also doing some job related with cardano. I want to run this project on server, but don't know how to start it up. Could you help me on how to start the improter? The README confused me.

**Comment by AlanVerbner** [comment]
hi @congle-ibl , @wangsai-silence 

Sorry for the delay. This is a known issue related to Cardano mas address length. We will push a fix soon that will allow you to continue syncing the blockchain although it will only be compatible with Icarus address style.

**Comment by wangsai-silence** [comment]
> hi @congle-ibl , @wangsai-silence
> 
> Sorry for the delay. This is a known issue related to Cardano mas address length. We will push a fix soon that will allow you to continue syncing the blockchain although it will only be compatible with Icarus address style.
hi @AlanVerbner 
Could you tell me more about how to start up the project? I am working on this for two days. And do not have any progress on it. I'm not good at Haskell. The README just tells me to run it from root project but not how to do it.
Thank you very much.

**Comment by AlanVerbner** [comment]
@wangsai-silence this are the steps to compile and launch (soon to be added to the README)

```bash
1) Install PostgresSQL and run the scripts from the following file: https://github.com/input-output-hk/project-icarus-importer/blob/icarus-master/scripts/generate/blockImporterTables-beta.sql 
2) `sudo apt-get install liblzma-dev libpq-dev`
3) `curl https://nixos.org/nix/install > install-nix.sh && . install-nix.sh`
4) `nix-build . -A connectScripts.mainnetBlockchainImporter -o importer-bin`
5) `./importer-bin - --runtime-args '--postgres-name importer --postgres-password mysecretpassword --no-tls' # Complete with the data you defined in step (1)
```

**Comment by mirkoAlic** [comment]
hi @congle-ibl , @wangsai-silence the fixes are already merged!

**Comment by wangsai-silence** [comment]
> @wangsai-silence this are the steps to compile and launch (soon to be added to the README)
> 
> ```shell
> 1) Install PostgresSQL and run the scripts from the following file: https://github.com/input-output-hk/project-icarus-importer/blob/icarus-master/scripts/generate/blockImporterTables-beta.sql 
> 2) `sudo apt-get install liblzma-dev libpq-dev`
> 3) `curl https://nixos.org/nix/install > install-nix.sh && . install-nix.sh`
> 4) `nix-build . -A connectScripts.mainnetBlockchainImporter -o importer-bin`
> 5) `./importer-bin - --runtime-args '--postgres-name importer --postgres-password mysecretpassword --no-tls' # Complete with the data you defined in step (1)
> ```

Thank you so much. I've already run it on server today. Great job.
